spring:
  application:
    name: bjt-api-server
  zipkin:
    base-url: http://${ZIPKIN_HOST:172.18.147.199}:9411/
    sender:
      type: web
    service:
      name: bjt-api
  sleuth:
    sampler:
     probability: 0.1
  #开启消息追踪
  cloud:
    bus:
      enabled: false
  ##### redis 支持RedisTemplate #####
  redis:
    database: 1
    host: ${REDIS_HOST:172.18.147.199}
    port: ${REDIS_PORT:6379}
    password: mWAeTehZJrn4lLbsDRU1CQ==
    jedis:
      pool:
        max-active: 60
server:
  port: 1004
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    # docker 部署开启
    prefer-ip-address: true
    ipAddress: ${INSTANCE_HOST:172.18.147.199}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:172.18.147.199}:${EUREKA_PORT:8761}/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder
  hystrix:
    enabled: true
##### redis 支持RedisUtil#####
master:
  redis:
    ip: ${REDIS_HOST:172.18.147.199}
    port: ${REDIS_PORT:6379}
    password: mWAeTehZJrn4lLbsDRU1CQ==
    max_active: 500
    max_idle: 5
    max_wait: 10000
    timeout: 10000

j4sc.auth.token-header: "j4sc-token"
billNotifyUrl: "http://172.18.147.199:1002"
carparkNotifyUrl: "http://172.18.147.199:1006"

imagePath: "/home/image/"