spring:
  application:
    name: bjt-api-server
  zipkin:
    base-url: http://192.168.0.118:9411/
    sender:
      type: web
    service:
      name: bjt-api
  sleuth:
    sampler:
     probability: 0.5
  #开启消息追踪
  cloud:
    bus:
      enabled: false
  ##### redis 支持RedisTemplate #####
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: G9Dbdjoc1B5kU2oD+gZy4w==
    jedis:
      pool:
        max-active: 60
server:
  port: 1004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder
  hystrix:
    enabled: true
##### redis 支持RedisUtil#####
master:
  redis:
    ip: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: G9Dbdjoc1B5kU2oD+gZy4w==
    max_active: 500
    max_idle: 5
    max_wait: 10000
    timeout: 10000

j4sc.auth.token-header: "j4sc-token"
billNotifyUrl: "http://192.168.0.112:1002"
carparkNotifyUrl: "http://192.168.0.112:1006"


imagePath: "d:\\image"